#!/usr/bin/bash
set -e
pushd ~/.nixos-config
nvim flake.nix
treefmt . &>/dev/null
git diff -U0 ./*.nix
echo "NixOS Rebuilding..."
sudo nixos-rebuild switch --flake .#test | tee ./nixos-switch.log >/dev/null || (
  grep --color error nixos-switch.log && false
)
gen=$(nixos-rebuild list-generations | grep current)
git commit -am "$gen"
popd
